import type { StampRecord } from '@/types/stamp'

export const SEED_STAMPS: StampRecord[] = [
  {
    id: 'seed-001',
    number: 1,
    slug: '1-founder-issue-toronto',
    creator_name: 'Santiago Barrera',
    creator_location: 'Toronto, Canada',
    message:
      'Kenzie, this first issue exists because you make ordinary days feel collectible. Keep this one. I will make the rest with everyone who loves you.',
    template: 'portrait',
    denomination: '1 pickle',
    composition_json: null,
    preview_url: null,
    source_photo_path: null,
    status: 'approved',
    created_at: '2026-08-20T16:00:00.000Z',
    approved_at: '2026-08-20T16:05:00.000Z',
    opened_at: null,
    seed_art: 'founder',
  },
  {
    id: 'seed-002',
    number: 2,
    slug: '2-sofia-toronto',
    creator_name: 'Sofia',
    creator_location: 'Toronto',
    message: 'One of my favourite things about you is how quickly a room becomes warmer when you walk into it.',
    template: 'circle',
    denomination: '1 hug',
    composition_json: null,
    preview_url: null,
    source_photo_path: null,
    status: 'approved',
    created_at: '2026-08-22T18:12:00.000Z',
    approved_at: '2026-08-22T18:40:00.000Z',
    opened_at: null,
    seed_art: 'rose',
  },
  {
    id: 'seed-003',
    number: 3,
    slug: '3-mara-montreal',
    creator_name: 'Mara',
    creator_location: 'Montreal',
    message: 'Remember the night we missed the last train and decided that was the correct itinerary.',
    template: 'tall',
    denomination: '1 memory',
    composition_json: null,
    preview_url: null,
    source_photo_path: null,
    status: 'approved',
    created_at: '2026-08-28T21:04:00.000Z',
    approved_at: '2026-08-29T09:00:00.000Z',
    opened_at: null,
    seed_art: 'train',
  },
  {
    id: 'seed-006',
    number: 6,
    slug: '6-julian-brooklyn',
    creator_name: 'Julian',
    creator_location: 'Brooklyn',
    message: 'Advice for the year ahead: keep ordering the strange thing on the menu.',
    template: 'square',
    denomination: '3 martinis',
    composition_json: null,
    preview_url: null,
    source_photo_path: null,
    status: 'approved',
    created_at: '2026-09-01T14:22:00.000Z',
    approved_at: '2026-09-01T15:10:00.000Z',
    opened_at: null,
    seed_art: 'olive',
  },
  {
    id: 'seed-009',
    number: 9,
    slug: '9-priya-london',
    creator_name: 'Priya',
    creator_location: 'London',
    message: 'You once made a terrible drawing of me and it is still on my fridge. I am returning the favour.',
    template: 'panoramic',
    denomination: '∞',
    composition_json: null,
    preview_url: null,
    source_photo_path: null,
    status: 'approved',
    created_at: '2026-09-03T11:48:00.000Z',
    approved_at: '2026-09-03T12:02:00.000Z',
    opened_at: null,
    seed_art: 'moon',
  },
  {
    id: 'seed-014',
    number: 14,
    slug: '14-alex-vancouver',
    creator_name: 'Alex',
    creator_location: 'Vancouver',
    message: 'Priceless is the only honest denomination for the way you remember people.',
    template: 'landscape',
    denomination: 'priceless',
    composition_json: null,
    preview_url: null,
    source_photo_path: null,
    status: 'approved',
    created_at: '2026-09-04T19:30:00.000Z',
    approved_at: '2026-09-04T20:00:00.000Z',
    opened_at: null,
    seed_art: 'letter',
  },
]

export function sealStamps(stamps: StampRecord[], unsealed: boolean): StampRecord[] {
  if (unsealed) return stamps
  return stamps.map((stamp) => ({ ...stamp, message: null }))
}
